import * as assert from "node:assert";
import { readFileSync } from "node:fs";
import { join } from "node:path";

import {
  handleCommandRequest,
  parseCommandRequest,
} from "../../providers/inspect/command-request";
import {
  parseContainerInventory,
  prepareSandboxOperation,
  SandboxOperation,
  sandboxTerminalArgs,
} from "../../providers/inspect/command-sandbox";

suite("Typed sandbox command requests", () => {
  const id = "a".repeat(64);
  const row = { id, name: "inspect-task-service-1" };
  const operation: SandboxOperation = {
    kind: "terminal",
    container: row.name,
    user: "1000:1000",
  };
  test("accepts the generated paired-producer translation fixture", () => {
    // Generated by executing the proposed helper against inspect_ai 03befb48.
    const wire: unknown = JSON.parse(
      readFileSync(
        join(__dirname, "../../../src/test/fixtures/command-ipc-producer.json"),
        "utf8"
      )
    );
    assert.deepStrictEqual(parseCommandRequest(wire), [
      { kind: "terminal", container: row.name },
      { kind: "attach", container: row.name },
    ]);
  });
  test("schema rejects command strings, shell text, options and unknown fields", () => {
    for (const payload of [
      { container: "--privileged" },
      { container: "a;b" },
      { container: "a", user: "root;id" },
      { container: "a", user: "--help" },
      { container: "a", command: "bash" },
      { container: "a", args: [] },
      { container: "a", user: null },
    ]) {
      assert.throws(() =>
        parseCommandRequest([
          { command: "inspect.openSandboxTerminal", args: [payload] },
        ])
      );
    }
    assert.throws(() =>
      parseCommandRequest([
        {
          command: "inspect.attachSandbox",
          args: [{ container: "a", user: "root" }],
        },
      ])
    );
    assert.deepStrictEqual(
      parseCommandRequest([
        {
          command: "inspect.openSandboxTerminal",
          args: [{ container: row.name, user: "1000:1000" }],
        },
      ]),
      [operation]
    );
  });
  test("requires daemon inventory and user target selection before effects", async () => {
    const effects: string[][] = [];
    const environment = {
      inventory: () => Promise.resolve([row]),
      choose: () => Promise.resolve(false),
      terminal: (target: string, user?: string) => {
        effects.push(sandboxTerminalArgs(target, user));
        return Promise.resolve();
      },
      attach: (target: string) => {
        effects.push(["attach", target]);
        return Promise.resolve();
      },
    };
    assert.strictEqual(
      await prepareSandboxOperation(operation, environment),
      undefined
    );
    await assert.rejects(
      prepareSandboxOperation(
        { ...operation, container: "unrelated" },
        { ...environment, choose: () => Promise.resolve(true) }
      )
    );
    assert.deepStrictEqual(effects, []);
    const run = await prepareSandboxOperation(operation, {
      ...environment,
      choose: (target) => {
        assert.strictEqual(target.id, id);
        return Promise.resolve(true);
      },
    });
    assert.deepStrictEqual(effects, []);
    await run!();
    assert.deepStrictEqual(effects, [
      ["exec", "-it", "--user", "1000:1000", id, "bash", "-l"],
    ]);
    const attach = await prepareSandboxOperation(
      { kind: "attach", container: row.name },
      { ...environment, choose: () => Promise.resolve(true) }
    );
    await attach!();
    assert.deepStrictEqual(effects[1], ["attach", id]);
  });
  test("container removal/name reuse after selection cannot retarget execution", async () => {
    let inventory = [row];
    const run = await prepareSandboxOperation(operation, {
      inventory: () => Promise.resolve(inventory),
      choose: () => Promise.resolve(true),
      terminal: () => {
        assert.fail("reused name executed");
      },
      attach: () => {
        assert.fail("unexpected attach");
      },
    });
    inventory = [{ ...row, id: "b".repeat(64) }];
    await assert.rejects(run!());
  });
  test("denial or invalid trailing requests prevents earlier log/sandbox effects", async () => {
    const batch = [
      { command: "inspect.openLogViewer", args: ["file:///tmp/run.eval"] },
      {
        command: "inspect.openSandboxTerminal",
        args: [{ container: row.name }],
      },
    ];
    const actions = {
      openLog: () => {
        assert.fail("partial batch effect");
      },
      prepareSandbox: () => Promise.resolve(undefined),
    };
    await handleCommandRequest(batch, actions);
    await assert.rejects(
      handleCommandRequest(
        [
          ...batch,
          {
            command: "workbench.action.terminal.sendSequence",
            args: [{ text: "id" }],
          },
        ],
        actions
      )
    );
  });
  test("daemon inventory is bounded and requires full container identities", () => {
    assert.deepStrictEqual(
      parseContainerInventory(JSON.stringify({ ID: id, Names: row.name })),
      [row]
    );
    assert.deepStrictEqual(parseContainerInventory(""), []);
    for (const output of [
      JSON.stringify({ ID: "abc", Names: "a" }),
      JSON.stringify({ ID: id, Names: "a;id" }),
      "{}\n".repeat(513),
    ])
      assert.throws(() => parseContainerInventory(output));
  });
});
