name: Release

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
      pull-requests: write
    uses: meridianlabs-ai/actions/.github/workflows/release-please-vscode.yml@v1
    with:
      extension-id: ukaisi.inspect-ai
    secrets: inherit
